[pytest]
pythonpath = .

markers =
    largest_element: tests for largest element problem
    second_largest: tests for second largest problem
    check_sorted_array: tests for check if the array is sorted
    remove_duplicates: tests for remove duplicates from sorted array
    left_rotate_by_one: tests for left rotate by one